name = "posture-detection-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "posture-detection-db"
database_id = "73fa16fd-d565-42db-b9fa-3b1d4ab8a1f6"
